[package]
name = "storage"
version = "0.1.1"
edition = "2021"

[lib]
name = "cranberry"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "^0.22.2", features = ["extension-module"] }
uuid = { version = "^1.10.0", features = [ "v4", "fast-rng", "macro-diagnostics"] }
