[package]
name = "cranberry"
version = "0.1.0"
edition = "2021"

[lib]
name = "cranberry"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.20.0", features = ["extension-module"], default-features = false }
numpy = "0.20.0"
rand = "0.8.4"

[profile.dev]
opt-level = 3
lto = "fat"
jemalloc = true
codegen-units = 1
codegen-units-std = 1
panic = "abort"
