on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

name: CI

jobs:
  ci:
    runs-on: ubuntu-latest
    name: Pass
    needs:
      - check_style_rust
      - check_style_python
      - test_rust
      - test_python
    steps:
      - run: exit 0

  check_style_rust:
    name: Check file formatting and style (Rust)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@nightly
        with:
          toolchain: nightly-2024-08-15
          components: rustfmt, clippy
      - uses: Swatinem/rust-cache@v2

      - name: Check file formatting
        run: cargo fmt --all -- --check
  
      - name: Run clippy
        run: cargo clippy --workspace --all-features
  
  check_style_python:
    name: Check file formatting and style (Python)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true
      - name: Set up Python
        run: uv python install 3.11
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
      - name: Sync deps
        run: uv sync --locked --dev

      - name: Ruff
        run: uv run ruff check .

      - name: Pyright
        run: uv run pyright
  
  test_rust:
    name: Tests (Rust)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@nightly
        with:
          toolchain: nightly-2024-08-15
      - uses: Swatinem/rust-cache@v2
  
      - name: Run tests
        run: cargo test --workspace --all-features

  test_python:
    name: Tests (Python)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true
      - name: Set up Python
        run: uv python install 3.11
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
      - name: Sync deps
        run: uv sync --locked --dev

      - name: Run tests
        run: uv run python -m pytest -v
