on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

name: Rust CI

jobs:
  ci:
    runs-on: ubuntu-latest
    name: "Pass"
    needs:
      - check_style
      - test
    steps:
      - run: exit 0
  
  check_style:
    name: Check file formatting and style
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          components: clippy, rustfmt

      - name: Check file formatting
        run: cargo fmt --all -- --check
  
      - name: Run clippy
        run: cargo clippy --workspace --all-features

  test:
    name: "Tests"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@nightly
        with:
          toolchain: nightly
  
      - name: Run tests
        run: cargo test --workspace --all-features
  